cf/urls.py
from django.contrib import admin
from django.urls import path

from web.views import rating,contests,contest,student

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', rating, name="rating"),
    path('contests', contests, name="contests"),
    path('contest/<int:contest_id>', contest, name="contest"),
    path('student/<str:cf_id>', student, name="student")
]

web/models.py
import datetime
from urllib import request

from django.db import models
from django.utils import timezone

from bs4 import BeautifulSoup


# Create your models here.

class Contest(models.Model):
    contest_id = models.IntegerField()
    name = models.CharField(max_length=200)
    start_time = models.DateTimeField(default=timezone.now)


class Student(models.Model):
    grade = models.CharField(max_length=200)
    name = models.CharField(max_length=200)
    cf_id = models.CharField(max_length=200)
    cf_rating = models.IntegerField(default=0)
    last_visit = models.DateTimeField(default=timezone.now)
    last_update_time = models.DateTimeField(default=timezone.now)
    contest = models.ManyToManyField('Contest', through='ContestStudent')

    def update(self):
        self.last_update_time = timezone.now()
        self.save()
        soup = BeautifulSoup(
            request.urlopen("http://codeforces.com/contests/with/%s" % self.cf_id, timeout=10).read().decode('utf-8'),
            'lxml')
        table = soup.find('table', class_='tablesorter user-contests-table').find('tbody')
        trs = table.find_all('tr')

        first = True
        for tr in trs:
            td = tr.find_all('td')

            contest_id = int(td[1].find('a')['href'].split('/')[-1].strip())  # id
            contest_name = td[1].get_text().strip()  # name

            contest_time = td[2].find('a').get_text().strip()  # time
            contest_time = datetime.datetime.strptime(contest_time, '%b/%d/%Y %H:%M') + datetime.timedelta(hours=5)
            contest_time = contest_time.replace(tzinfo=datetime.timezone(datetime.timedelta(hours=0)))

            contest = Contest.objects.get_or_create(contest_id=contest_id, name=contest_name, start_time=contest_time)
            contest = contest[0]

            rank = int(td[3].get_text().strip())
            solved = int(td[4].find('a').get_text().strip())
            rating_change = int(td[5].find('span').get_text().strip())
            new_rating = int(td[6].get_text().strip())

            if first:
                first = False
                self.cf_rating = new_rating
                self.last_update_time = timezone.now()
                self.save()

            if len(self.contest.filter(contest_id=contest_id)) == 0:
                ContestStudent(contest=contest,
                               student=self,
                               rank=rank,
                               solved=solved,
                               rating_change=rating_change,
                               new_rating=new_rating).save()

    @property
    def color(self):
        if self.cf_rating < 1200:
            return "grey"
        if self.cf_rating < 1400:
            return "green"
        if self.cf_rating < 1600:
            return "#03A89D"
        if self.cf_rating < 1900:
            return "blue"
        if self.cf_rating < 2100:
            return "#AA00AA"
        if self.cf_rating < 2400:
            return "#FF8C00"
        if self.cf_rating < 4000:
            return "red"

    @property
    def last_five(self):
        res = []
        contests = self.conteststudent_set.all().order_by("-contest__start_time")
        for contest in contests:
            if len(res) == 5:
                break
            res.append(contest.new_rating)

        res.reverse()
        return str(res)

    def __str__(self):
        return str([self.name, self.cf_id, self.cf_rating])


class ContestStudent(models.Model):
    contest = models.ForeignKey(Contest, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    rank = models.IntegerField()
    solved = models.IntegerField()
    rating_change = models.IntegerField()
    new_rating = models.IntegerField()

web/views.py
from django.shortcuts import render

# Create your views here.

from .models import Student, Contest, ContestStudent


# Create your views here.
def rating(request):
    return render(request, "rating.html", {"students": Student.objects.all().order_by('-cf_rating')})


def contests(request):
    return render(request, "contests.html", {"contests": Contest.objects.all().order_by('-start_time')})


def contest(request, contest_id):
    return render(request, "contest.html",
                  {"conteststudens": ContestStudent.objects.filter(contest__contest_id=contest_id).order_by('rank'),
                   "contest": Contest.objects.get(contest_id=contest_id)})

def student(request, cf_id):
    return render(request, "student.html",
                  {"conteststudents":ContestStudent.objects.filter(student__cf_id=cf_id).order_by('contest__start_time'),
                   "student": Student.objects.get(cf_id=cf_id)})

templates/contest.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{{ contest.contest_id }}</title>
</head>

{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<body>

<nav class="navbar navbar-expand-lg fixed-top navbar-light bg-light">
    <div class="container-fluid">
        <a href="{% url 'rating' %}" class="navbar-brand"><strong>CUST ACM</strong></a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav nav-tabs">
                <li class="nav-item">
                    <a class = "nav-link" href="{% url 'rating' %}">Rating</a>
                </li>
                <li class="nav-item">
                    <a class = "nav-link" href="{% url 'contests' %}">Contests</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<br>
<br>
<br>

<div class="page-header text-center h1 text-secondary">
    {{ contest.name }}
</div>

<table style="width:80%;margin:0px auto;" class="table align-middle table-striped border">
    <thead>
    <th>#</th>
    <th>年级</th>
    <th>姓名</th>
    <th>CFID</th>
    <th>rank</th>
    <th>solved</th>
    <th>rating change</th>
    <th>new rating</th>
    </thead>
    <tbody>
    {% for conteststudent in conteststudens %}
        <tr style="height:50px;" class="table-bordered">
            <td class="col-md-1">{{  forloop.counter }}</td>
            <td>{{ conteststudent.student.grade }}</td>
            <td>{{ conteststudent.student.name }}</td>
{#            <td style="color:{{ conteststudent.student.color }};font-family: Monaco, monospace" >{{ conteststudent.student.cf_id }}</td>#}
            <td style=";font-family: Monaco, monospace;">
                <a href="{% url 'student' conteststudent.student.cf_id %}" style="text-decoration: none;color:{{ conteststudent.student.color }}">{{ conteststudent.student.cf_id }}</a>
            </td>

            <td>{{ conteststudent.rank }}</td>
            <td>{{ conteststudent.solved }}</td>
            <td style="color:{% if conteststudent.rating_change > 0 %}green{% else %}grey{% endif %};font-weight:bold;">
                {% if conteststudent.rating_change > 0 %}+{% endif %}{{ conteststudent.rating_change }}
            </td>
            <td>{{ conteststudent.new_rating }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

</body>
</html>

templates/contests.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>contests</title>
</head>

{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}


<nav class="navbar navbar-expand-lg fixed-top navbar-light bg-light">
    <div class="container-fluid">
        <a href="{% url 'rating' %}" class="navbar-brand"><strong>CUST ACM</strong></a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav nav-tabs">
                <li class="nav-item">
                    <a class = "nav-link" href="{% url 'rating' %}">Rating</a>
                </li>
                <li class="nav-item">
                    <a class = "nav-link active" href="{% url 'contests' %}">Contests</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<br>
<br>
<br>

<table style="width:80%;margin:0px auto;" class="table align-middle table-striped border">
    <thead>
    <th class="col-md-2">Contest ID</th>
    <th class="col-md-6">Name</th>
    <th class="col-md-2">Time</th>
    <th class="col-md-2">人数</th>
    </thead>
    <tbody>
   	{% for contest in contests %}
        <tr style="height: 50px">
            <td>{{  contest.contest_id }}</td>
            <td><a href="{% url 'contest' contest.contest_id%}" style="text-decoration: none;">{{ contest.name }}</a> </td>
            <td>{{ contest.start_time|date:"Y-m-d H:i"}}</td>
            <td>{{ contest.student_set.count }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

</body>
</html>

templates/rating.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}

    <title>Rating</title>
</head>

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.min.js"></script>

<script>
     x = function () {
        var chartInstance = this.chart,
            ctx = chartInstance.ctx;
        ctx.textAlign = 'center';
        ctx.textBaseline = 'bottom';
        this.data.datasets.forEach(function (dataset, i) {
            var meta = chartInstance.controller.getDatasetMeta(i);
            meta.data.forEach(function (bar, index) {
                var data = dataset.data[index];
                ctx.font = "bold 12px Arial";
                let Y = bar._model.y
                if(Y<15)Y+=15
                let X = bar._model.x-15
                if(index == 0) X += 30
                ctx.fillText(data,X,Y);
            });
        });
    };
    opt = {
        scales: {
            xAxes: [
                {
                    display: false,
                }
            ], yAxes: [
                {
                    display: false,
                }
            ]
        },
        events: false,
        tooltips: {
            enabled: false
        },
        hover: {
            animationDuration: 0
        },
        animation: {
            duration: 1,
            onComplete: x,
        }
    };
    Chart.defaults.global.legend.display = false;
    Chart.defaults.scale.gridLines.display = false;
</script>

<body>

<nav class="navbar navbar-expand-lg fixed-top navbar-light bg-light">
    <div class="container-fluid">
        <a href="{% url 'rating' %}" class="navbar-brand"><strong>CUST ACM</strong></a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav nav-tabs">
                <li class="nav-item">
                    <a class = "nav-link active" href="{% url 'rating' %}">Rating</a>
                </li>
                <li class="nav-item">
                    <a class = "nav-link" href="{% url 'contests' %}">Contests</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<br>
<br>
<br>
<table style="width:80%;margin:0px auto;" class="table align-middle table-striped border">
    <thead>
    <th class="col-md-1">#</th>
    <th class="col-md-1">年级</th>
    <th class="col-md-1">姓名</th>
    <th class="col-md-3">CF ID</th>
    <th class="col-md-1">rating</th>
    <th class="col-md-1">次数</th>
    <th class="col-md-3">最近五场</th>
    </thead>
    <tbody>
    {% for student in students %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ student.grade }}</td>
            <td>{{ student.name }}</td>
            <td style=";font-family: Monaco, monospace;">
                <a href="{% url 'student' student.cf_id %}" style="text-decoration: none;color:{{ student.color }}">{{ student.cf_id }}</a>
            </td>
{#            <td style="color:{{ student.color }};font-family: Monaco, monospace">{{ student.cf_id }}</td>#}
            {% if student.contest.count != 0 %}
                <td>{{ student.cf_rating }}</td>
            {% else %}
                <td>快去打</td>
            {% endif %}

            <td>{{ student.contest.count }}</td>
            <td>
                <div style="width:300px;position: relative;">
                    <canvas id="canvas-{{ student.cf_id }}" width="400" height="100"></canvas>
                </div>
            </td>
        </tr>
        <script>
                var ctx = document.getElementById("canvas-{{ student.cf_id }}").getContext("2d");
                var myChart = new Chart(ctx, {
                    pointDot: false,
                    type: 'line',
                    data: {
                        labels: ['','','','',''],
                        datasets: [{
                            pointRadius: 2,
                            fill: false,
                            pointBackgroundColor: "black",
                            data: {{ student.last_five }}
                        }]
                    },
                    options: opt
                });
        </script>
    {% endfor %}
    </tbody>

</table>

</body>
</html>

templates/student.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{{ student.name }}</title>
</head>

{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}


<nav class="navbar navbar-expand-lg fixed-top navbar-light bg-light">
    <div class="container-fluid">
        <a href="{% url 'rating' %}" class="navbar-brand"><strong>CUST ACM</strong></a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav nav-tabs">
                <li class="nav-item">
                    <a class = "nav-link" href="{% url 'rating' %}">Rating</a>
                </li>
                <li class="nav-item">
                    <a class = "nav-link" href="{% url 'contests' %}">Contests</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<br>
<br>
<br>

<div class="page-header text-center h1 text-secondary">
    {{ student.name }} <span style="color: {{ student.color }}">{{ student.cf_id }}</span>
</div>

<table style="width:80%;margin:0px auto;" class="table align-middle table-striped border">
    <thead>
    <th class="col-md-1">Contest ID</th>
    <th class="col-md-5">Name</th>
    <th class="col-md-2">Time</th>
    <th class="col-md-2">rating change</th>
    <th class="col-md-1">new rating</th>
    </thead>
    <tbody>
   	{% for conteststudent in conteststudents %}
        <tr style="height: 50px">
            <td>{{ conteststudent.contest.contest_id }}</td>
            <td><a href="{% url 'contest' conteststudent.contest.contest_id%}" style="text-decoration: none;">{{ conteststudent.contest.name }}</a> </td>
            <td>{{ conteststudent.contest.start_time|date:"Y-m-d H:i"}}</td>
            <td style="color:{% if conteststudent.rating_change > 0 %}green{% else %}grey{% endif %};font-weight:bold;">
                {% if conteststudent.rating_change > 0 %}+{% endif %}{{ conteststudent.rating_change }}
            </td>
            <td>{{ conteststudent.new_rating }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

</body>
</html>